import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "@/components/layouts/Footer";
import Navbar from "@/components/layouts/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "website generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* <ClerkLoading>
            <div className="flex items-center justify-center min-h-screen text-2xl">
              LOADING...
            </div>
          </ClerkLoading> */}

          {/* <ClerkLoaded> */}
          <div className=" bg-gray-200 min-h-screen max-w-[1400px] mx-auto px-3 pt-4">
            <Navbar />
            <div className="min-h-screen sm:px-6 mt-14 ">{children}</div>
            <Footer />
          </div>
          {/* </ClerkLoaded> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
